Marks={
    "History":{
        "A":12,
        "B":13,
        "C":23,
        "D":34,
        "E":21
        },
    "Geography":{
        "A":12,
        "B":13,
        "C":23,
        "D":34,
        "E":21
        }
    }
print(Marks)
